version: "3.8"

services:
  php:
    build:
      dockerfile: php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./../:/var/www/html:delegated

  nginx:
    image: nginx:1.19.4-alpine
    volumes:
      - ./../public:/var/www/html/public:delegated
      - ./nginx/default.conf:/etc/nginx/templates/default.conf.template:delegated
    ports:
      - 80:80